### ISSUE TITLE
map does not rotate to the driving direction the vehicle is going.

### ISSUE THREAD

**Issue by trippah** [ffwdme/ffwdme.js#11]
All turn-by-turn navigation allows map to rotate to the direction the driver is going. It makes the user experience much more natural and easier to understand. Is it possible to add this feature?

**Comment by fabrik42** [comment]
Hi!

There is an experimental component, called `MapRotator`, that tries to do this. 
https://github.com/ffwdme/ffwdme.js/blob/master/src/components/map_rotator/index.js

It is disabled by default in the demo: https://github.com/ffwdme/ffwdme.js/blob/master/static/demo/app.js#L40-L41

You can give it a try and report back what you think.
Of course, if you find a better solution, I would be happy to hear about it as well.


Best,

Christian

**Comment by trippah** [comment]
Since leaflet core doesn't support rotation, when you rotate with CSS leaflet will not work properly, (ie. cannot click map to get coordinate).

I am trying to convert from leaflet to openlayers 3 as it natively supports rotation but their documentation is really bad :-1:

**Comment by fabrik42** [comment]
Yes, this is true :(

If you get openlayers working with ffwdme.js I would be happy to integrate it or link to it as a 3rd party component.

Let me know, if you need any further assistance!


Cheers,

Christian

**Comment by fabrik42** [comment]
Hey @trippah 

I was looking into https://www.mapbox.com/mapbox-gl-js/api/ lately - maybe this could be an alternative?

I would be very interested to bring this kind of technology to ffwdme.

What do you think?


Cheers,

Christian

**Comment by trippah** [comment]
@fabrik42 looks very promising, i'm going to take a look into it :+1:

**Comment by fabrik42** [comment]
Awesome! Let me know, if I can help you out with something.


Best,
Christian

**Comment by trippah** [comment]
@fabrik42 I am current working on this project and borrowing some parts from ffwdme. I hope this is ok. https://bitbucket.org/SyntheticOrg/synthauto/

**Comment by fabrik42** [comment]
Hi,
this looks like a pretty cool project! It's ok for me if you use some parts of ffwdme.
It would be nice, if you could include a backlink to this project in the Readme file.

Best,

Christian

**Comment by trippah** [comment]
no problems will mention you

**Comment by fabrik42** [comment]
Thank you!

**Comment by sweco-semhul** [comment]
Hi, @fabrik42 have any more work been done to add support for mapbox gl js to this project?
Curious to know before I start coding it :)

**Comment by fabrik42** [comment]
Sorry - I didn't even start. 
It would be awesome, if you could give it a try. If I can support you in any way, let me know. :)

**Comment by sweco-semhul** [comment]
Thanks for fast response. I´m giving it a try. My plan is to move some parts out of the leaflet class, creating a base map class. And then a new example

**Comment by sweco-semhul** [comment]
Thanks for fast response. I´m giving it a try. 
My plan is to move some parts out of the leaflet class, creating a base map class. And then also extend it with a new class for mapboxgl and a new demo map for it.

**Comment by fabrik42** [comment]
Sounds good. I'm not familiar enough with the mapboxgl API, so I'm not sure how much there is to refactor. Just give it a try and we will see how much abstraction is useful in this case :)
