### ISSUE TITLE
gulp is not running

### ISSUE THREAD

**Issue by buddhishan** [ffwdme/ffwdme.js#15]
Im new to node and gulp but want to implement turn by turn navigation. I have downloaded the zip. Have node installed. I installed all dependencies on the extracted folder. I typed 'gulp' in cmd to run gulp for a local preview server. But it ends with some errors. 

```
E:\CycleMate\App\ffwd>gulp

module.js:341
    throw err;
    ^

Error: Cannot find module '../../secrets.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\CycleMate\App\ffwd\gulp\tasks\deploy.js:3:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

E:\CycleMate\App\ffwd>
```

Please let me know where I have gone wrong. Thank you in advance

**Comment by fabrik42** [comment]
You need to copy the [secrets_example.json](https://github.com/ffwdme/ffwdme.js/blob/master/secrets_example.json) to `secrets.json`. No need to fill real values in yet.

Sorry, I think I need to make this clearer in the docs. Let me know if there is anything else you need to get started.

**Comment by fabrik42** [comment]
(closing this for now, fell free to reopen or create another issue, if you face more problems)

**Comment by buddhishan** [comment]
Thank you very much for your information. Im really impressed that it worked. I could goto localhost and find. But the demo.html does not show the map. It says 'wait for geolocation'. What might be the problem? 

When I access the dev.ffwdmejs.org/demo.html, it works fine!  

You are really appreciated if you can help me because Im a new bee to this field and badly want this to be implemented. Thank you in advance!

**Comment by fabrik42** [comment]
Hi,
you are welcome :)

Did you allow the page to use the geolocation of the browser? Did you see the prompt?

It should look like this when you start the demo app for the first time using `gulp`. (my browser language is German, but the interface should look the same)

![bildschirmfoto 2016-03-16 um 16 40 42](https://cloud.githubusercontent.com/assets/223822/13818386/fbfa0fa0-eb95-11e5-93b5-0f4985b01ca7.png)

You have to allow the demo page to use your geolocation. If you do, you should see the map after a few seconds and you should see a debug output in your JavaScript console:

![bildschirmfoto 2016-03-16 um 16 40 56](https://cloud.githubusercontent.com/assets/223822/13818456/34e13dac-eb96-11e5-9279-cf5faa5a7cc2.png)

Hope this helps!

**Comment by buddhishan** [comment]
Hello,

I figured out what went wrong. I haven't correctly updated the MapBox
token. BTW Thank you very much and you have being amazing. Its working fine
now :) :D Im developing a navigation app using ffwdme and will keep you in
touch in future :) Thanks again for the source code.

**Comment by fabrik42** [comment]
No problem,
let me know when you have any further questions. I'm always curious what people build with ffwdme, so if there is something to see, hit me up :)
