### ISSUE TITLE
toString() is considered unsafe in a Cordova application

### ISSUE THREAD

**Issue by WallyDoodlez** [ffwdme/ffwdme.js#2]
I am using ffwdme in my experimental cordova application, and cordova is blocking toString() method calls and deems it as an unsafe method. This is at least occurring windows/windows phone devices.

As a result, when ffwdme tries to create a new instance of LatLng object, it will fail.

``` javascript
if (Array.isArray(lat) == "array"){
  //if (toString.call(lat) === '[object Array]') {
    lng = lat[1];
    lat = lat[0];
  }

```

**Comment by fabrik42** [comment]
This is new to me. The LatLng class basically calls `Object.prototype.toString`. This is a very common pattern to test for arrays. 

What we could do is to test for the native `Array.isArray()` function of modern browsers first. And only use this as a fallback or remove it completely. http://kangax.github.io/compat-table/es5/#Array.isArray

Do you have any information available about cordova blocking `toString`? - A quick google search returned nothing.

**Comment by WallyDoodlez** [comment]
I should clarify the problem. 
Initially I thought it has something to do with Cordova, it might not be the issue. To be precise, I am encountering the same problem as described here:

http://stackoverflow.com/questions/20884457/ie-11-throws-exceptions-when-debugging-responsive-web-app-with-bootstrap-in-visu

When toString.call(lat) is called, it goes to that code described in the stackoverflow.
It does seem like its likely an issue in IE.

**Comment by fabrik42** [comment]
Sorry but I don't see how these two problems are related. 
Could you post your browser/version and the specific error message?

**Comment by fabrik42** [comment]
Closing this for now. Please reopen if there is anything new to report.

Cheers,
Christian
