### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by maeishoj** [ffwdme/ffwdme.js#22]
Hey there.

I was wondering if you could help me figure out why the map doesn't look so good on retina. it is very blurry and online i ready you have to add "detectRetina: true" in the tileLayer. However when you do that, the map looks sharper, but as you zoom in, the details like labels, street names etc are way too small..

**Comment by fabrik42** [comment]
Sorry, but I have no idea what could cause this. Maybe this is a general problem, so if you find a solution it would be great if you could share it!

**Comment by fabrik42** [comment]
Closing this until we have more information at hand. Please reopen if you find out something :)
