### ISSUE TITLE
How to refresh cursor more often?

### ISSUE THREAD

**Issue by maeishoj** [ffwdme/ffwdme.js#23]
Hi there.

Is there a way to refresh the cursors more often? it makes huge jumps and it hardly ever refreshes.... Is this something i have to do manually myself by polling location often?

**Comment by fabrik42** [comment]
Hi :)

The update frequency of the GPS position is not determined by ffwdme itself but by the runtime/OS. ffwdme just uses the `watchposition` method: https://github.com/ffwdme/ffwdme.js/blob/master/src/core/geolocation.js#L95-L99

Can you tell me which device you are using?

**Comment by maeishoj** [comment]
I was trying this from my mac while driving in the car, as I did not have an ipad at hand. Ideally though this will be used from an ipad.. Although I was connected to my iPhone hotspot..

**Comment by fabrik42** [comment]
Ok, a Mac will update the GPS position very slowly. Using an iPad with active GPS sensor, the position should update about twice a second while moving.

For testing on a Mac, you may want to look at the GeoProvider package: https://github.com/ffwdme/ffwdme.js/tree/master/src/debug/geoprovider

It provides tools to record and replay positions for local development.

**Comment by maeishoj** [comment]
Thanks I Will look into that!
