### ISSUE TITLE
Audio instructions in a web view (ios)

### ISSUE THREAD

**Issue by OrKoN** [ffwdme/ffwdme.js#30]
Hello,

I was wondering if audio instructions can work in a web view on iOS? I could not get them working. Any suggestions?

Thanks,
Alex

**Comment by fabrik42** [comment]
Hi Alex!
Sorry, I don't have experience with iOS development. Did you try to create a barebone example without ffwdme, just using the HTML Audio APIs?

Best,
Christian

**Comment by OrKoN** [comment]
@fabrik42 actually I made it work in the meantime. The missing part for me was to include this in `AppDelegate.m`:

```
#import <AVFoundation/AVFoundation.h>

  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
  NSError *setCategoryError = nil;
  [audioSession setCategory:AVAudioSessionCategoryPlayback
                      error:&setCategoryError];
```

in addition to allowing the playback on the WebView component itself. Basically, it works now with audio instructions but it seems it is a bit slower inside a web view compared to a normal mobile browser like Chrome + when you play recorded routes, the marker on the map often jumps back and forth quite often.

**Comment by fabrik42** [comment]
Very cool, you made it work!

I am not an iOS developer, but I think [it depends on the kind of web view, you are embedding](http://developer.outbrain.com/ios-best-practices-for-opening-a-web-page-within-an-app/).

However, ffwdme normally does not need very much resources, it should run smoothly in an iPhone 3G Safari. So maybe there some other problem causing the jumpings?
