### ISSUE TITLE
Voice Audio 

### ISSUE THREAD

**Issue by Angelbrat79** [ffwdme/ffwdme.js#32]
Hi, 

Can the voice on the directions be in English ?

**Comment by fabrik42** [comment]
Yes, you just would have to record your own audio file and set the right timestamps in the `voice.json` file.

For examples, see here: https://github.com/ffwdme/ffwdme.js/tree/master/src/components/audio_instructions/voices

The audio files (ending with `m4a`, `mp3`, `ogg`, `wav`) are all the same content, just different audio encoding.

So basically, there is only one audio file, that contains all the voice instructions. It is an audio sprite, containing all the voices with silence in between. The `voice.json` file contains the timestamps of the single instructions. After you recorded your own voice, you would need to adjust the values in this file.

Let me know, if you have any more questions.

**Comment by mm-ns** [comment]
I find that using audio file is a little archaic and tedious. What I do instead is write in a div the turn directions from graphhopper (you can get them in multiple languages) and then i use the browser built in HTML5 Speech Synthesizer to make it ready the road directions.

**Comment by fabrik42** [comment]
Sure, this is another way to make this work! Feel free to contribute a component, if you like :)

**Comment by fabrik42** [comment]
Closing this for now.
