### ISSUE TITLE
Auto Zoom vs Non Auto Zoom

### ISSUE THREAD

**Issue by mm-ns** [ffwdme/ffwdme.js#34]
Hi there

How would the map behave if I don't use auto zoom? as the marker moves does the map re-centers automatically on the cursor?

**Comment by fabrik42** [comment]
Hi!
Yes it does, the part of the code responsible for this can be seen [here](https://github.com/ffwdme/ffwdme.js/blob/master/src/components/leaflet/index.js#L199-L207).

Please reopen this or another issue, if you have any more questions. :)
