### ISSUE TITLE
how to use it with cordova/phonegap

### ISSUE THREAD

**Issue by Dhamu143** [ffwdme/ffwdme.js#36]
as i have seen that on this GitHub page it has the whole project there is no libaray that we can include it in our project and call their functions. even that is also not compiled perfectly.
I am using Cordova/PhoneGap  how can I use this ffwdme.js with cordova ?

**Comment by fabrik42** [comment]
Hi! You are right we are discussing a better build tooling here: https://github.com/ffwdme/ffwdme.js/issues/17

Feel free to provide feedback in the issue.

Meanwhile, I think to easiest solution would be to download the lib and place it into a vendor folder, outside of any package management system?

If you have any special requirements, please let me know in the issue linked above! :)

**Comment by fabrik42** [comment]
Closing this for now. Please re-open if there is anything else. :)
