### ISSUE TITLE
Align map view so that marker is close to the bottom

### ISSUE THREAD

**Issue by mm-ns** [ffwdme/ffwdme.js#37]
Hi There.

How do I allow the cursor to be more towards the bottom of the page like in the regular gps navigation styles?

**Comment by fabrik42** [comment]
Hi! You would need to modify the [component responsible for the map](https://github.com/ffwdme/ffwdme.js/blob/master/src/components/leaflet/index.js). There is no built in solution for this, so you would need to provide a solution on your own.

**Comment by fabrik42** [comment]
Closing this for now
