### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by jptheripper** [ffwdme/ffwdme.js#39]
I am looking for the api.  For example, in the initialize method it takes an object, and you give the example of Grasshopper but say others are supported.  How do i find the "others"?

**Comment by fabrik42** [comment]
Hi there!

I am sorry, right now there are no other routing options available. But the interfaces are ready for a custom implementation!

Please have a look at this ticket, where I describe the process of implementing your own routing service: https://github.com/ffwdme/ffwdme.js/issues/33

**Comment by jptheripper** [comment]
I appreciate the response.  I will take a look at it.  I think i understand
the concept, just have to figure out where to put the custom code

Jeff

**Comment by jptheripper** [comment]
Having trouble installing .  Erroring on bessdsv module.  ideas?

25725 verbose stack Error: Command failed: git -c core.longpaths=true clone
--template=C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\_templates
--mirror git://github.com/bessdsv/bower-installer.git
C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818
25725 verbose stack Cloning into bare repository
'C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818'...
25725 verbose stack fatal: read error: Invalid argument
25725 verbose stack
25725 verbose stack     at ChildProcess.exithandler
(child_process.js:199:12)
25725 verbose stack     at emitTwo (events.js:106:13)
25725 verbose stack     at ChildProcess.emit (events.js:191:7)
25725 verbose stack     at maybeClose (internal/child_process.js:920:16)
25725 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:230:5)
25726 verbose cwd C:\ffwdme.js\ffwdme.js
25727 error Windows_NT 10.0.14393
25728 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
25729 error node v6.12.3
25730 error npm  v3.10.10
25731 error code 128
25732 error Command failed: git -c core.longpaths=true clone
--template=C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\_templates
--mirror git://github.com/bessdsv/bower-installer.git
C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818
25732 error Cloning into bare repository
'C:\Users\jpace\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818'...
25732 error fatal: read error: Invalid argument
25733 error If you need help, you may report this error at:
25733 error     <https://github.com/npm/npm/issues>
25734 verbose exit [ 1, true ]

**Comment by fabrik42** [comment]
Sorry, I can not reproduce your error. Which command exactly failed? What is your node/npm version?

```
➜  node --version
v9.8.0
➜  npm --version
5.6.0
```

**Comment by fabrik42** [comment]
Closed due to inactivity.
