### ISSUE TITLE
giolocation not working on a desktop browser

### ISSUE THREAD

**Issue by liorfr** [ffwdme/ffwdme.js#5]
Hi,

First of all, this project is great !

When I am  running the project with “gulp default” the app is loading via loacalhost (http://localhost:3000/demo.html?debug=true) and the giolocation work just fine.

When I am loading the index.html via file on the desktop (file:///C:/Workspaces/ffwdme.js/build/demo.html?debug=true#) the giolocation is not working. I want to package the build folder with cordova and run it as an app on an android but I am having the giolocation problem both on the desktop browser and on the android app

How can I fix this issue

Thanks 
Lio

**Comment by fabrik42** [comment]
Hi,
you should not load the Page using the `file` protocol, but the server provided by gulp, via `localhost`.

Once you've built the files, you should also access them using a webserver. Either something like Apache/nginx or, for example, just upload it to the Public folder of Dropbox/Google Drive and use the generated link.

Let me know, if this helps. If not, can you provide some errors or JS `console` output of the demo page?

Best,
Christian

**Comment by fabrik42** [comment]
Any updates on this?

**Comment by liorfr** [comment]
Yes.
I am using the http-server (https://www.npmjs.com/package/http-server) and it works great.

To run locally without a server I am running Chrome with the following command from the cmd :
chrome -–allow-file-access-from-files
