### ISSUE TITLE
Map pivot

### ISSUE THREAD

**Issue by liorfr** [ffwdme/ffwdme.js#6]
Hi,

How can I make the map pivot according to the driving direction ?  I would the arrow always to point up

Thanks 
Lio

**Comment by fabrik42** [comment]
Hi!

Take a look at the `MapRotator` component. :)
You can find it here: https://github.com/ffwdme/ffwdme.js/tree/master/src/components/map_rotator
On the demo page, it is disabled by default: https://github.com/ffwdme/ffwdme.js/blob/master/static/demo/app.js#L41

Let me know, if this works for you :)

**Comment by liorfr** [comment]
I get an exception in 
...\components\leaflet\index.js
exception function name: setMapContainerSize()
exception in line: this.el && this.el.animate({ rotate: rotate + 'deg' });
the exception text is:
exception text: this.el.animate is not a function

Are you working on the rotator feature ?

Thanks 
Lio

**Comment by fabrik42** [comment]
This component relies on zepto.js. I don't work on the feature right now. 
If you need it, it would be great, if you could give it a try and implement it.

You can use the existing component as a starting point. The error occurs here:
https://github.com/ffwdme/ffwdme.js/blob/master/src/components/map_rotator/index.js#L38

Maybe you could switch the zepto part for vanilla JS and work with CSS-Transitions instead?
