### ISSUE TITLE
Checking if GPS is enable....

### ISSUE THREAD

**Issue by Neoespecialistas** [ffwdme/ffwdme.js#9]
Hi,

I'm trying to check if GPS is enable.
I tryed this code:

---

function init(){
ffwdme.initialize({});
     });

ffwdme.on('geoposition:error', function() {
     alert('Please, put GPS active');
      });

etc...

---

But never alert me that GPS is disabled.

What is wrong ?

Thanks in advance,
David

**Comment by fabrik42** [comment]
You should try to register the `geoposition:error` event before initializing `ffwdme`.

``` js
function init(){
  ffwdme.on('geoposition:error', function() {
    alert('Please, put GPS active');
  });
  ffwdme.initialize({});
});
```

Compare: https://github.com/ffwdme/ffwdme.js/blob/master/static/demo/app.js#L3-L18

**Comment by Neoespecialistas** [comment]
Thanks a bunch !
David
